version: '3'

services:
  
  vuejs:
    build: ./simple-login-project
    volumes:
      - ./simple-login-project:/usr/src/app/
    ports:
      - "8080:80"
    networks: 
      mynet:
        ipv4_address: "172.16.238.10"
    depends_on: 
      - mysqldb
    links: 
      - mysqldb

  mysqldb:
    image: mysql:5.7
    container_name: mysql-vuejs
    ports: 
      - "3306:3306"    
    networks:
      mynet:
        ipv4_address: "172.16.238.11"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d/
    restart: always


networks: 
  mynet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24